CREATE TABLE DeviceData
(
	[Device Name] VARCHAR(50) NOT NULL PRIMARY KEY, 
    [Peak Load] FLOAT NULL, 
	[Duty Cycle] FLOAT NULL,
    [Average Load_1] FLOAT NULL, 
    [Average Load_2] FLOAT NULL, 
    [Average Load_3] FLOAT NULL, 
    [Average Load_4] FLOAT NULL, 
    [Average Load_5] FLOAT NULL, 
    [Average Load_6] FLOAT NULL, 
    [Average Load_7] FLOAT NULL, 
    [Average Load_8] FLOAT NULL, 
    [Average Load_9] FLOAT NULL, 
    [Average Load_10] FLOAT NULL, 
    [Average Load_11] FLOAT NULL, 
    [Average Load_12] FLOAT NULL, 
    [Average Load_13] FLOAT NULL, 
    [Average Load_14] FLOAT NULL, 
    [Average Load_15] FLOAT NULL, 
    [Average Load_16] FLOAT NULL, 
    [Average Load_17] FLOAT NULL, 
    [Average Load_18] FLOAT NULL, 
    [Average Load_19] FLOAT NULL, 
    [Average Load_20] FLOAT NULL, 
    [Average Load_21] FLOAT NULL, 
    [Average Load_22] FLOAT NULL, 
    [Average Load_23] FLOAT NULL, 
    [Average Load_24] FLOAT NULL 
)
